export default {
  countryCode: "vn",
  countryName: "Vietnam",
  countryEmoji: "\u{1F1FB}\u{1F1F3}", // 🇻🇳

  languages: ["en", "vi"],
  defaultLanguage: "en",

  title: "Vietnam Knowledge Graph",
  subtitle: "Exploring {n} WikiData entities: history, geography, people & culture",

  splashTitle: "\u{1F1FB}\u{1F1F3} MiniDi",
  splashMessage: "Loading Vietnam knowledge graph...",

  slides: [
    {
      label: "Hạ Long Bay", lang: "en",
      labelAlt: "Vịnh Hạ Long", langAlt: "vi",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Halong_Bay_in_2019.jpg/1280px-Halong_Bay_in_2019.jpg",
      grad: "linear-gradient(135deg, #0f766e, #0d9488, #2dd4bf)",
    },
    {
      label: "Hoàng Sa Archipelago", lang: "en",
      labelAlt: "Quần đảo Hoàng Sa", langAlt: "vi",
      img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
      grad: "linear-gradient(135deg, #1e3a5f, #2563eb, #60a5fa)",
    },
    {
      label: "Hội An Ancient Town", lang: "en",
      labelAlt: "Phố cổ Hội An", langAlt: "vi",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Hoi_An_Ancient_Town_at_dusk.jpg/1280px-Hoi_An_Ancient_Town_at_dusk.jpg",
      grad: "linear-gradient(135deg, #7c2d12, #dc2626, #fbbf24)",
    },
    {
      label: "Mekong Delta", lang: "en",
      labelAlt: "Đồng bằng sông Cửu Long", langAlt: "vi",
      img: "https://images.unsplash.com/photo-1598970605070-a38a6ccd1a2d?w=1200&q=80",
      grad: "linear-gradient(135deg, #14532d, #16a34a, #86efac)",
    },
    {
      label: "Huế Imperial City", lang: "en",
      labelAlt: "Cố đô Huế", langAlt: "vi",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Hue_Citadel.jpg/1280px-Hue_Citadel.jpg",
      grad: "linear-gradient(135deg, #4a1d96, #8b5cf6, #c084fc)",
    },
    {
      label: "Sa Pa Terraces", lang: "en",
      labelAlt: "Ruộng bậc thang Sa Pa", langAlt: "vi",
      img: "https://images.unsplash.com/photo-1528127269322-539801943592?w=1200&q=80",
      grad: "linear-gradient(135deg, #3b82f6, #1d4ed8, #93c5fd)",
    },
  ],

  mapCenter: [16, 107.5],
  mapZoom: 6,

  eras: [
    {
      id: "hong_bang",
      emoji: "\u{1F3DB}",
      label: { en: "Hồng Bàng Dynasty", vi: "Thời kỳ Hồng Bàng" },
      years: [-2879, -258],
      color: "#8b5cf6",
    },
    {
      id: "chinese_domination",
      emoji: "\u{1F30F}",
      label: { en: "Chinese Domination", vi: "Bắc thuộc" },
      years: [-111, 939],
      color: "#ef4444",
    },
    {
      id: "dynastic_vn",
      emoji: "\u{1F451}",
      label: { en: "Dynastic Vietnam", vi: "Việt Nam thời quân chủ" },
      years: [939, 1858],
      color: "#f59e0b",
    },
    {
      id: "colonial",
      emoji: "\u{2696}",
      label: { en: "French Colonial Period", vi: "Pháp thuộc" },
      years: [1858, 1954],
      color: "#3b82f6",
    },
    {
      id: "vietnam_war",
      emoji: "\u{1F4A5}",
      label: { en: "Vietnam War / American War", vi: "Chiến tranh Việt Nam" },
      years: [1955, 1975],
      color: "#dc2626",
    },
    {
      id: "modern",
      emoji: "\u{1F4F7}",
      label: { en: "Modern Vietnam", vi: "Việt Nam hiện đại" },
      years: [1975, 9999],
      color: "#22c55e",
    },
  ],

  githubRepo: "minidivn/minidi-vn-data",
  dataSource: "WikiData",

  dataPath: "index.json",

  chatCountry: "Vietnam",
  chatGreeting: "Ask me about Vietnam — history, people, places, events.",

  translations: {
    en: {
      entities: "Entities",
      events: "Events",
      people: "People",
      places: "Places",
      all: "All",
      search: "Search...",
      noResults: "No matching entities",
      loading: "Loading...",
      results: "{n} results",
      page: "Page {p} of {t}",
      prev: "Prev",
      next: "Next",
      details: "Details",
      relations: "Relations",
      wiki: "Open in WikiData",
      timeline: "Timeline",
      tree: "Dynasty Tree",
      builtWith: "Built with",
      source: "source",
      chatTitle: "MiniDi Assistant",
      chatPlaceholder: "Ask about Vietnam...",
      entitiesTotal: "{n} entities",
      mapPlaces: "Places",
      mapPeople: "People",
      mapEvents: "Events",
    },
    vi: {
      entities: "Thực thể",
      events: "Sự kiện",
      people: "Nhân vật",
      places: "Địa danh",
      all: "Tất cả",
      search: "Tìm kiếm...",
      noResults: "Không tìm thấy",
      loading: "Đang tải...",
      results: "{n} kết quả",
      page: "Trang {p} / {t}",
      prev: "Trước",
      next: "Sau",
      details: "Chi tiết",
      relations: "Quan hệ",
      wiki: "Mở trong WikiData",
      timeline: "Thời gian",
      tree: "Đồng hồ",
      builtWith: "Xây dựng với",
      source: "Mã nguồn",
      chatTitle: "Trợ lý MiniDi",
      chatPlaceholder: "Hỏi về Việt Nam...",
      entitiesTotal: "{n} thực thể",
      mapPlaces: "Địa danh",
      mapPeople: "Nhân vật",
      mapEvents: "Sự kiện",
    },
  },
};
